#!/bin/sh
set -e

lb config noauto \
    --distribution bookworm \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer none \
    --binary-images iso-hybrid \
    --iso-application "AnyBoot Live System" \
    --iso-preparer "AnyBoot Project <https://github.com/mikl0s/anyboot>" \
    --iso-publisher "AnyBoot Project" \
    --iso-volume "AnyBoot_Live" \
    --memtest none \
    --updates true \
    --security true \
    --backports false \
    --bootappend-live "boot=live components persistence persistence-storage=filesystem username=anyboot hostname=anyboot" \
    --linux-flavours amd64 \
    --chroot-filesystem squashfs \
    "${@}"
